### ISSUE TITLE
Clicking "Open" in the toolbar opens up a console window, instead of the lab

### ISSUE THREAD

**Issue by robdom** [learn-co-curriculum/hello-world-ruby#68] opened 2016-06-29 17:50 UTC
When I click "Open" in the toolbar for the "Hello World Ruby" lab, a console window opens up instead of the lab in the Learn app.

I'm using Mac OS X 10.11.5, Google Chrome Version 51.0.2704.103 (64-bit).

Here's a screenshot:

![fullscreen_6_29_16__1_43_pm](https://cloud.githubusercontent.com/assets/13624584/16462635/1947eb7e-3e00-11e6-8bbc-bc89a6580336.jpg)

**Comment by pletcher** [comment] 2016-06-29 17:50
Thanks for being a part of the Learn community!

Keep in mind that this space is for specific issues related to the content of this lesson.

If you're reporting on the content of this lesson, it'd be super helpful if you could include a stack trace of any errors that you're seeing.

If you'd like to report a bug about the Learn IDE, the Ask a Question form, opening a file, or the lights not working on Learn, please report a bug directly on https://learn.co. (You can find the bug report form by clicking on your avatar in the upper right, and then selecting "Report A Bug".)

We want to respond as quickly as possible and be as helpful as possible, so please be sure to include steps to reproduce the issue (as best you can remember) and any pertinent details about your environment. (Are you using the Learn IDE? Coding from the ISS?) We'll figure out what's up and get back to you ASAP.

**Comment by kvignali** [comment] 2016-06-29 17:57
hey @robdom this is actually not a bug with this specific lesson, but something going on in your environment. Thanks for reporting a bug, we can communicate over email to resolve it. I am going to close this issue out since it's not specific to the lab.

**Closed as completed by kvignali** 2016-06-29 17:57 UTC
